# Note: This is duplicated from thread-sanitizer.yml in order to keep the ci running if one of both sanitizers fail
name: Address Sanitizer Test

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linux-address-sanitizer-gcc:
    name: Linux GCC Address Sanitizer Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ["debian:bookworm-slim", "debian:bullseye-slim", "ubuntu:kinetic"]
    env:
      SANITIZER_SKIP_SUMMARY: 1

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install, build and run sanitizer tests
        run: ./docker-compose.sh test-address-sanitizer
        env:
          METACALL_BASE_IMAGE: ${{ matrix.image }}
