name: Metacall Benchmarks

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
      - develop
      - benchmark_ci
      
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [windows-2019]
          options: [
            {build: debug, sanitizer: without-sanitizer}
          ]
          benchs : [
            metacall-py-call-bench.json, 
            metacall-py-init-bench.json,
            metacall-py-c-api-bench.json,
            # metacall-cs-call-bench.json,
            # metacall-node-call-bench.json,
            # metacall-rb-call-bench.json
            ]
          
    env:
      LTTNG_UST_REGISTER_TIMEOUT: 0
      NUGET_XMLDOC_MODE: skip
      DOTNET_CLI_TELEMETRY_OPTOUT: "true"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Activate the Visual Studio Developer Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
        if: matrix.os == 'windows-2019'

      - name: Prepare variables (macOS/Linux)
        run: |
          # Extract the OS name from matrix.os
          OS_NAME=$(echo ${{ matrix.os }} | sed 's/-latest$//')
          BENCH_NAME=$(echo ${{ matrix.benchs }} | sed 's/metacall-\(.*\)-bench.json/\1/')
          # Set the OS_NAME environment variable for use in subsequent steps
          echo "OS_NAME=${OS_NAME}" >> $GITHUB_ENV
          echo "BENCH_NAME=${BENCH_NAME}" >> $GITHUB_ENV
        if: matrix.os != 'windows-2019'

      - name: Prepare variables (Windows)
        run: |
          # Extract the OS name from matrix.os
          $env:OS_NAME = $env:matrix_os -replace '-latest$', ''
          # Extract the benchmark name from matrix.benchs
          $env:BENCH_NAME = $env:matrix_benchs -replace 'metacall-(.*?)-bench.json', '$1'
          # Set the OS_NAME environment variable for use in subsequent steps
          echo "OS_NAME=$env:OS_NAME" | Out-File -FilePath $env:GITHUB_ENV -Append
          # Set the BENCH_NAME environment variable for use in subsequent steps
          echo "BENCH_NAME=$env:BENCH_NAME" | Out-File -FilePath $env:GITHUB_ENV -Append
        if: matrix.os == 'windows-2019'
          
      - name: Set up the environment (macOS/Linux)
        run: |
          sh ./tools/metacall-environment.sh $METACALL_INSTALL_OPTIONS
        env:
          METACALL_INSTALL_OPTIONS: base python backtrace 
        if : matrix.os != 'windows-2019'

      - name: Set up the environment (Windows)
        run: cmd.exe /c "powershell .\tools\metacall-environment.ps1 $Env:METACALL_INSTALL_OPTIONS"
        env:
          METACALL_INSTALL_OPTIONS: python
        if: matrix.os == 'windows-2019'

      - name: Configure (macOS/Linux)
        run: |
          mkdir -p build
          cd build
          if [ "$(uname)" == "Darwin" ]; then
            . .env
          fi
          bash ../tools/metacall-configure.sh $METACALL_CONFIGURE_OPTIONS
        env:
          METACALL_CONFIGURE_OPTIONS: ${{ matrix.options.build }} ${{ matrix.options.sanitizer }} scripts ports tests python benchmarks install 
        if: matrix.os != 'windows-2019'

      - name: Configure
        run: |
          $METACALL_PATH = $PWD
          md -Force "$METACALL_PATH\build"
          cd "$METACALL_PATH\build"
          cmd.exe /c "powershell ..\tools\metacall-configure.ps1 $Env:METACALL_BUILD_OPTIONS"
        env:
          METACALL_BUILD_OPTIONS: ${{ matrix.options.build }} ${{ matrix.options.sanitizer }} scripts ports tests python 
        if: matrix.os == 'windows-2019'

      - name: Build (macOS/Linux)
        working-directory: ./build
        # TODO: Remove the disable option for fork safe once funchook problem is solved
        run: |
          if [ "$(uname)" == "Darwin" ]; then
            . .env
          fi
          cmake -DOPTION_FORK_SAFE=OFF  ..
          bash ../tools/metacall-build.sh $METACALL_BUILD_OPTIONS
        env:
          METACALL_BUILD_OPTIONS: ${{ matrix.options.build }} tests
        if: matrix.os != 'windows-2019'

      - name: Build (Windows)
        working-directory: ./build
        run: cmd.exe /c "powershell ..\tools\metacall-build.ps1 $Env:METACALL_BUILD_OPTIONS"
        env:
          METACALL_BUILD_OPTIONS: ${{ matrix.options.build }} tests
        if: matrix.os == 'windows-2019'

      - name: List files in build directory (windows)
        run: |
          $METACALL_PATH = $PWD
          cd "$METACALL_PATH\build"
          ls
        if: matrix.os == 'windows-2019'

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
            name: Metacall ${{ env.OS_NAME }}-${{ env.BENCH_NAME }} Benchmark
            tool: 'googlecpp'
            output-file-path: ./build/${{ matrix.benchs }}
            # Access token to deploy GitHub Pages branch
            github-token: ${{ secrets.GITHUB_TOKEN }}
            # Push and deploy GitHub pages branch automatically
            auto-push: true
            # Github Pages branch name
            gh-pages-branch: pages
            # Comment in case of alert
            comment-on-alert: true
            benchmark-data-dir-path: bench/${{ env.OS_NAME }}/${{ env.BENCH_NAME }}
